//Name: Delaney Wozniak
//Class:INFO 2200
//Section: X01
//Professor: Sharp
//Date: 2/19/2024
//Project #: Participation 3
//By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
//I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
//I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _2200_WozniakD_Participation03
{
    /// <summary>
    /// created Plant class and its three properties
    /// </summary>
    public class Plant
    {
        // created three properties specific to Plant class only
        private string _environment;
        private string _type;
        private string _name;

        // created constructor method to make variables readable and writeable
        public Plant(string env, string typ, string nm) 
        {
            _environment = env;
            _type = typ;
            _name = nm;
        }
        public string Name
        {
            get { return _name; } // made Name readable
            set { _name = value; } // made Name writeable
        }
        public string Enviornment
        {
            get { return _environment; } // made Enviornment readable
            set { _environment = value; } // made Environment writeable
        }
        public string Type
        {
            get { return _type; } // made Type readable
            set { _type = value; } // made type writeable
        }

        public virtual string Sniff() // create virtual string method for Sniff
        {
            return "Lets sniff plants";
        }
    }
}
