using System;
using System.Collections.Generic;
using System.Linq;
//Name: Delaney Wozniak
//Class:INFO 2200
//Section: X01
//Professor: Sharp
//Date: 2/19/2024
//Project #: Participation 3
//By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
//I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
//I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace _2200_WozniakD_Participation03
{
    /// <summary>
    /// Interaction logic for PlantDetailsWindow.xaml
    /// </summary>
    public partial class PlantDetailsWindow : Window
    {
        public Plant SelectedPlant { get; set; } // created public variable SelectedPlant and made it readable and writeable
        public PlantDetailsWindow()
        {
            InitializeComponent();
        }
        /// <summary>
        /// click event and sniff method
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnSniff_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show(SelectedPlant.Sniff()); // show Sniff method
        }
    }
}
