#Name: Delaney Wozniak
#Class:INFO 2200
#Section: X01
#Professor: Sharp
#Date: 01/23/2024
#Project #: 01
#By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment.
#I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.)
#nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.).
#I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

#!/usr/bin/env python3

def main():
    #main function to search for user input in the dictionary and display it
    print("Welcome to Delaney's College Search App") #welcome message
    print() #empty line
    userinput = input("Please enter a college and I will return the city. (x to exit, random to get a Random College/City): ") #get user input

    colleges = "" 
    while userinput.lower() != "x": #while loop to search dictionary for users input
        with open("colleges.txt") as file: #read colleges.txt
            collegeDict = {} #create dictionary
            for line in file: #find user input and corresponding city
                line = line.replace("\n","") #search for city using user input
                tempcollege = line.split(",") #read each line
                collegeDict.update({tempcollege[0]:tempcollege[1]}) #update

        userCollege = userinput.title() #declare userCollege as userinput
        if userCollege in collegeDict: 
            print() #empty line
            print(f"College: {userCollege}") #display user input
            print(f"City: {collegeDict[userCollege]}") #display user input corresponding college city
            print()#empty line
        import random

        rand = random.Random() #random class
        totalColleges = rand.randint(0, len(collegeDict)) #fetch size of dictionary
        randCollege = list(collegeDict.keys())[totalColleges] #retrieve random key
        randcity = collegeDict.get(randCollege)
        if randcity is not None:
            print(f"Random College: {randCollege}, {randcity}") #display college and city
            
        else: #display error message if college is not in dictionary
            print(f"Could not find {userinput} in the database") #error message
            print() #empty line        

        userinput = input("Please enter a college and I will return the city. (x to exit, random to get a Random College/City): ") #get user input
    print("Goodbye!") #goodbye message
    

if __name__ == "__main__": main() #main funtion call
