///Name: Delaney Wozniak
///Class: INFO 2200
///Section: X01
///Professor: Sharp
///Date: 01/18/2024
///Project #: 01
///By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
///I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
///I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _2200_WozniakD_Participation01
{
    internal class Program
    {
        /// <summary>
        /// Creates dictionary and adds text file to it. Recieves user input and searches for corresponding response.
        /// </summary>
        /// <param name="args"></param>
        static void Main(string[] args)
        {
            Console.WriteLine("Welcome to Delaney's State Capital Lookup App"); //Display welcome message
            Console.WriteLine(); //empty line

            Console.Write("Please enter a state and I will return the capital (x to exit): "); //display prompt
            string userinput = Console.ReadLine(); //get user input

            Dictionary<string, string> stateCapDict = new Dictionary<string, string>(); //new dictionary

            StreamReader reader = new StreamReader("statecaps.txt"); //read statecaps text file
            while (!reader.EndOfStream) //while loop to add text file to dictionary
            {
                string line = reader.ReadLine(); //read all lines of text file
                string[] tempstatecaps = line.Split(','); //
                string state = tempstatecaps[0]; //add states to dictionary
                string capital = tempstatecaps[1]; //add capitals to dictionary
                stateCapDict.Add(state.ToUpper(), capital); //add all states and capitals to dictionary
            }
            reader.Close(); //stop reading text file

            //while loop to search for users input in dictionary
            while (userinput != "x")
            {
                if(stateCapDict.TryGetValue(userinput.ToUpper(), out string cap))
                {
                    Console.WriteLine(); //empty line
                    Console.WriteLine($"State: {userinput}"); //display user input state
                    Console.WriteLine($"Capital: {cap}"); //display capital
                    Console.WriteLine(); //empty line
                }
                else
                {
                    Console.WriteLine($"Could not find {userinput} in the database"); //display error message
                    userinput = Console.ReadLine(); //read user input
                }
            }
        }
    }
}