using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
///Name: Delaney Wozniak
///Class: INFO 2200
///Section: X01
///Professor: Sharp
///Date: 03/26/2024
///Project #: Participation 5
///By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
///I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
///I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

namespace _2200_WozniakD_Participation05
{
    public partial class AddProductForm : Form
    {
        ProductEntityDb db = new ProductEntityDb(); // connect to db
        public AddProductForm()
        {
            InitializeComponent();
        }
        /// <summary>
        /// Click event for add product form
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void AddProductForm_Load(object sender, EventArgs e)
        {
            CbCategory.Items.Add("New Category"); //create new category
            var catItems = (from cat in db.Products
                            where cat.Category != null
                            group cat.Category by cat.Category into c
                            select new { Category = c.Key }); //create category variable with uniques keys
            CbCategory.Items.AddRange(catItems.Select(cats => cats.Category).ToArray()); //select the category and add to array
        }
        /// <summary>
        /// Selected change event for combo box
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void CbCategory_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (CbCategory.SelectedIndex == 0) //if category is found show text box and label
            {
                TxtBoxNew.Show();
                LblNewCategory.Show();
            }
            else //if category is not found, hide text box and label
            {
                TxtBoxNew.Hide();
                LblNewCategory.Hide();
            }
        }
        /// <summary>
        /// Click event for cancel button
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnCancel_Click(object sender, EventArgs e)
        {
            decimal price; //price as decimal
            int uoh; //units on hand as integer

            if (TxtBoxDesc.Text.Trim() != "" && 
                decimal.TryParse(TxtBoxPrice.Text, out price) && 
                int.TryParse(TxtBoxUnits.Text, out uoh) &&
                CbCategory.SelectedIndex > -1) //if price and units on hand are decimals and is greater than -1 create new product
            {
                Product newprod = new Product //create new product
                {
                    Category = CbCategory.SelectedIndex == 0 ? TxtBoxNew.Text : CbCategory.SelectedItem.ToString(), //validate category or new category
                    Description = TxtBoxDesc.Text, //validate description text in text box
                    Price = price, //validate price for new product
                    Product_Number = TxtBoxProdNum.Text, //validate new product number
                    Units_On_Hand = uoh //validate units on hand for new product
                };
                db.Products.Add(newprod); //add new product to db
                db.SaveChanges(); //update db

                MessageBox.Show($"{newprod.Product_Number} was just added to the database."); //display message
                Close();
            }
            else
            {
                MessageBox.Show($"Please enter data for all inputs."); //display error message
            }
        }
    }
}
