using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Windows.Forms;
///Name: Delaney Wozniak
///Class: INFO 2200
///Section: X01
///Professor: Sharp
///Date: 03/26/2024
///Project #: Participation 5
///By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
///I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
///I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

namespace _2200_WozniakD_Participation05
{
    public partial class CategoryForm : Form
    {
        ProductEntityDb db = new ProductEntityDb(); //connect to db
        public CategoryForm()
        {
            InitializeComponent();
        }
        /// <summary>
        /// Load event for category form
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void CategoryForm_Load(object sender, EventArgs e)
        {
            LvCategories.Columns.Add("Category"); //add column category in list view
            LvCategories.Columns.Add("Count"); //add column category count in list view
            List<CatTotalViewModel> catTotals = (from cat in db.Products
                                                 group cat.Category by cat.Category into cats
                                                 select new CatTotalViewModel { ProdCat = cats.Key, CatCount = cats.Count() }).ToList(); //counts categories and lists all of them and their counts from the database
            //List<CatTotalViewModel> linqMethod = db.Products.GroupBy(cat => cat.Category).Select(cats => new CatTotalViewModel { ProdCat = cats.Key, CatCount = cats.Count()}).ToList();
            foreach (CatTotalViewModel item in catTotals)
            {
                string[] listitems = { item.ProdCat, item.CatCount.ToString() }; //find each category from db
                ListViewItem lvi = new ListViewItem(listitems); //create new list item for evey category
                LvCategories.Items.Add(lvi); //add categories to listview
            }
            LvCategories.AutoResizeColumn(0, ColumnHeaderAutoResizeStyle.HeaderSize); //auto resize listview
            LvCategories.AutoResizeColumn(1, ColumnHeaderAutoResizeStyle.HeaderSize); //auto resize listview
        }
    }
    /// <summary>
    /// Class to view category counts
    /// </summary>
    public class CatTotalViewModel
    {
        public string ProdCat { get; set; } //product category
        public int CatCount { get; set;} //category count
    }
}
