using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
///Name: Delaney Wozniak
///Class: INFO 2200
///Section: X01
///Professor: Sharp
///Date: 03/26/2024
///Project #: Participation 5
///By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
///I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
///I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

namespace _2200_WozniakD_Participation05
{
    public partial class ProductForm : Form
    {
        public ProductForm()
        {
            InitializeComponent();
        }
        /// <summary>
        /// Click event for product search button
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnProdSearch_Click(object sender, EventArgs e)
        {
            ProductSearchForm productSearchForm = new ProductSearchForm(); 
            productSearchForm.ShowDialog(); //displays product search form
        }
        /// <summary>
        /// Click event for group by category button
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnGroupCat_Click(object sender, EventArgs e)
        {
            CategoryForm categoryForm = new CategoryForm();
            categoryForm.ShowDialog(); // displays category form
        }
    }
}
