using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
///Name: Delaney Wozniak
///Class: INFO 2200
///Section: X01
///Professor: Sharp
///Date: 04/04/2024
///Project #: Participation 6
///By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
///I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
///I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

namespace ServerApplication
{
    class Program
    {
        static void Main(string[] args)
        {
            TempServer tempServer = new TempServer(); //connect to TempServer
            tempServer.LoadFiles(); //load all files

            Console.WriteLine("Welcome to Delaney's joke/Conspiracy Server"); //display welcome message
            Console.WriteLine("-------------------------------------------");

            SyncronousSocketListener ssl = new SyncronousSocketListener(); //read file
            ssl.StartListening(); //sit in memory until user sends something over
        }
    }
}
