using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
///Name: Delaney Wozniak
///Class: INFO 2200
///Section: X01
///Professor: Sharp
///Date: 04/04/2024
///Project #: Participation 6
///By submitting this assignment, I declare that the source code contained in this assignment was written solely by me, unless specifically provided in the assignment. 
///I attest that no part of this assignment, in whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Bard, Copilot, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). 
///I understand that copying any source code, in whole or in part, constitutes cheating, and that I will receive a zero on this project if I am found in violation of this policy.

namespace ServerApplication
{
    public class TempServer
    {
        Random rand = new Random(); //random function
        string[] jokes; //string array for jokes
        string[] conspiracies; //string array for conspiracies
        const string JOKE_FILE = "jokes.txt"; //constant string for jokes.txt file
        const string CONSP_FILE = "conspiracies.txt"; //constant string for conspiracies.txt file
        public TempServer()
        {
           
        }
        public void LoadFiles() //load all files
        {
            try
            {
                jokes = File.ReadAllLines(JOKE_FILE); //read all lines of joke file
                conspiracies = File.ReadAllLines(CONSP_FILE); //read all lines of conspiracy file
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message); //display ex error message
            }
        }
        public string GetRandomJoke()
        {
            return jokes[rand.Next(jokes.Length)]; //get random joke
        }
        public string GetRandomConsp()
        {
            return conspiracies[rand.Next(conspiracies.Length)]; //get random conspiracy
        }
    }
}
